// <auto-generated />
using System;
using MecuryProduct.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecuryProduct.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240527034613_AddMasterVehicleTable")]
    partial class AddMasterVehicleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MecuryProduct.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("driverId")
                        .HasColumnType("int");

                    b.Property<string>("oldThreePasswords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MecuryProduct.Data.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_not_running_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_run")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("car_year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("checkNo")
                        .HasColumnType("int");

                    b.Property<int?>("cid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("dnd_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driver_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lead_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motor_condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("offered_ammount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("pickup_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("prod_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pull_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pull_type_des")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("pulled_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("purchase_amount")
                        .HasColumnType("int");

                    b.Property<string>("row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("scheduled_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("set_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("special_instructions")
                        .HasColumnType("bit");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("submitted_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tires_wheel_front")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tires_wheel_rear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("title_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vin_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("cid");

                    b.HasIndex("created_by_id");

                    b.HasIndex("driver_id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("MecuryProduct.Data.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("caddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ccity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ccountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cfname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("clat")
                        .HasColumnType("float");

                    b.Property<string>("clname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("clon")
                        .HasColumnType("float");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_prefrence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cphone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cstate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("czip_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("created_by_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MecuryProduct.Data.DocModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("server_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sf_id")
                        .HasColumnType("int");

                    b.Property<string>("short_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("veh_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("sf_id")
                        .IsUnique()
                        .HasFilter("[sf_id] IS NOT NULL");

                    b.HasIndex("veh_id");

                    b.ToTable("Docs");
                });

            modelBuilder.Entity("MecuryProduct.Data.MasterProductionTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterProductionTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            row = "1",
                            section = "SP"
                        },
                        new
                        {
                            Id = 2,
                            row = "2",
                            section = "SP"
                        },
                        new
                        {
                            Id = 3,
                            row = "3",
                            section = "SP"
                        },
                        new
                        {
                            Id = 4,
                            row = "4",
                            section = "SP"
                        },
                        new
                        {
                            Id = 5,
                            row = "5",
                            section = "SP"
                        },
                        new
                        {
                            Id = 6,
                            row = "6",
                            section = "SP"
                        },
                        new
                        {
                            Id = 7,
                            row = "7",
                            section = "SP"
                        },
                        new
                        {
                            Id = 8,
                            row = "8",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 9,
                            row = "9",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 10,
                            row = "10",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 11,
                            row = "11",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 12,
                            row = "12",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 13,
                            row = "13",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 14,
                            row = "14",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 15,
                            row = "15",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 16,
                            row = "16",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 17,
                            row = "17",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 18,
                            row = "18",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 19,
                            row = "19",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 20,
                            row = "20",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 21,
                            row = "21",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 22,
                            row = "22",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 23,
                            row = "23",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 24,
                            row = "24",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 25,
                            row = "25",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 26,
                            row = "26",
                            section = "CH"
                        },
                        new
                        {
                            Id = 27,
                            row = "27",
                            section = "CH"
                        },
                        new
                        {
                            Id = 28,
                            row = "28",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 29,
                            row = "29",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 30,
                            row = "30",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 31,
                            row = "31",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 32,
                            row = "32",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 33,
                            row = "33",
                            section = "GM"
                        },
                        new
                        {
                            Id = 34,
                            row = "34",
                            section = "GM"
                        },
                        new
                        {
                            Id = 35,
                            row = "35",
                            section = "GM"
                        },
                        new
                        {
                            Id = 36,
                            row = "36",
                            section = "GM"
                        },
                        new
                        {
                            Id = 37,
                            row = "37",
                            section = "GM"
                        },
                        new
                        {
                            Id = 38,
                            row = "38",
                            section = "GM"
                        },
                        new
                        {
                            Id = 39,
                            row = "39",
                            section = "GM"
                        },
                        new
                        {
                            Id = 40,
                            row = "40",
                            section = "GM"
                        },
                        new
                        {
                            Id = 41,
                            row = "41",
                            section = "GM"
                        },
                        new
                        {
                            Id = 42,
                            row = "42",
                            section = "GM"
                        },
                        new
                        {
                            Id = 43,
                            row = "43",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 44,
                            row = "44",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 45,
                            row = "45",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 46,
                            row = "46",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 47,
                            row = "47",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 48,
                            row = "48",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 49,
                            row = "8B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 50,
                            row = "9B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 51,
                            row = "10B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 52,
                            row = "11B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 53,
                            row = "12B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 54,
                            row = "13B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 55,
                            row = "14B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 56,
                            row = "15B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 57,
                            row = "16B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 58,
                            row = "17B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 59,
                            row = "18B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 60,
                            row = "19B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 61,
                            row = "20B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 62,
                            row = "21B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 63,
                            row = "22B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 64,
                            row = "23B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 65,
                            row = "24B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 67,
                            row = "25B",
                            section = "IMP"
                        },
                        new
                        {
                            Id = 68,
                            row = "26B",
                            section = "CH"
                        },
                        new
                        {
                            Id = 69,
                            row = "27B",
                            section = "CH"
                        },
                        new
                        {
                            Id = 70,
                            row = "28B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 71,
                            row = "29B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 72,
                            row = "30B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 73,
                            row = "31B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 74,
                            row = "32B",
                            section = "T&V"
                        },
                        new
                        {
                            Id = 75,
                            row = "33B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 76,
                            row = "34B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 77,
                            row = "35B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 78,
                            row = "36B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 79,
                            row = "37B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 80,
                            row = "38B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 81,
                            row = "39B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 82,
                            row = "40B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 83,
                            row = "41B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 84,
                            row = "42B",
                            section = "GM"
                        },
                        new
                        {
                            Id = 85,
                            row = "43B",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 86,
                            row = "44B",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 87,
                            row = "45B",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 88,
                            row = "46B",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 89,
                            row = "47B",
                            section = "FORD"
                        },
                        new
                        {
                            Id = 90,
                            row = "48B",
                            section = "FORD"
                        });
                });

            modelBuilder.Entity("MecuryProduct.Data.MasterVehicleTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterVehicleTable");
                });

            modelBuilder.Entity("MecuryProduct.Data.MasterYearTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MasterYearTable");
                });

            modelBuilder.Entity("MecuryProduct.Data.NoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerModelId")
                        .HasColumnType("int");

                    b.Property<string>("corrected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corrected_byId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("corrected_by_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("corrected_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("veh_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerModelId");

                    b.HasIndex("corrected_byId");

                    b.HasIndex("created_by_id");

                    b.HasIndex("veh_id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MecuryProduct.Data.StateFormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StateForm");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MecuryProduct.Data.CarModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.CustomerModel", "customer")
                        .WithMany("cars")
                        .HasForeignKey("cid");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "created_by")
                        .WithMany("cars")
                        .HasForeignKey("created_by_id");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "driver")
                        .WithMany("driver_cars")
                        .HasForeignKey("driver_id");

                    b.Navigation("created_by");

                    b.Navigation("customer");

                    b.Navigation("driver");
                });

            modelBuilder.Entity("MecuryProduct.Data.CustomerModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", "created_by")
                        .WithMany("customers")
                        .HasForeignKey("created_by_id");

                    b.Navigation("created_by");
                });

            modelBuilder.Entity("MecuryProduct.Data.DocModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.StateFormModel", "state_form")
                        .WithOne("doc")
                        .HasForeignKey("MecuryProduct.Data.DocModel", "sf_id");

                    b.HasOne("MecuryProduct.Data.CarModel", "car")
                        .WithMany("docs")
                        .HasForeignKey("veh_id");

                    b.Navigation("car");

                    b.Navigation("state_form");
                });

            modelBuilder.Entity("MecuryProduct.Data.NoteModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.CustomerModel", null)
                        .WithMany("notes")
                        .HasForeignKey("CustomerModelId");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "corrected_by")
                        .WithMany()
                        .HasForeignKey("corrected_byId");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "created_by")
                        .WithMany("notes")
                        .HasForeignKey("created_by_id");

                    b.HasOne("MecuryProduct.Data.CarModel", "vehicle")
                        .WithMany("notes")
                        .HasForeignKey("veh_id");

                    b.Navigation("corrected_by");

                    b.Navigation("created_by");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MecuryProduct.Data.ApplicationUser", b =>
                {
                    b.Navigation("cars");

                    b.Navigation("customers");

                    b.Navigation("driver_cars");

                    b.Navigation("notes");
                });

            modelBuilder.Entity("MecuryProduct.Data.CarModel", b =>
                {
                    b.Navigation("docs");

                    b.Navigation("notes");
                });

            modelBuilder.Entity("MecuryProduct.Data.CustomerModel", b =>
                {
                    b.Navigation("cars");

                    b.Navigation("notes");
                });

            modelBuilder.Entity("MecuryProduct.Data.StateFormModel", b =>
                {
                    b.Navigation("doc");
                });
#pragma warning restore 612, 618
        }
    }
}
