// <auto-generated />
using System;
using MecuryProduct.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecuryProduct.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240509062702_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MecuryProduct.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MecuryProduct.Data.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_not_running_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_run")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("car_year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("checkNo")
                        .HasColumnType("int");

                    b.Property<int?>("cid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("dnd_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driver_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lead_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motor_condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("offered_ammount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("pickup_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pull_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pull_type_des")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("purchase_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("scheduled_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("special_instructions")
                        .HasColumnType("bit");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("submitted_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tires_wheel_front")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tires_wheel_rear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("title_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vin_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vin_picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("cid");

                    b.HasIndex("created_by_id");

                    b.HasIndex("driver_id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("MecuryProduct.Data.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("caddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ccity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ccountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cfname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_prefrence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cphone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cstate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("czip_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("created_by_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MecuryProduct.Data.NoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerModelId")
                        .HasColumnType("int");

                    b.Property<string>("corrected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corrected_byId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("corrected_by_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("corrected_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("veh_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerModelId");

                    b.HasIndex("corrected_byId");

                    b.HasIndex("created_by_id");

                    b.HasIndex("veh_id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MecuryProduct.Data.CarModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.CustomerModel", "customer")
                        .WithMany("cars")
                        .HasForeignKey("cid");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "created_by")
                        .WithMany("cars")
                        .HasForeignKey("created_by_id");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "driver")
                        .WithMany("driver_cars")
                        .HasForeignKey("driver_id");

                    b.Navigation("created_by");

                    b.Navigation("customer");

                    b.Navigation("driver");
                });

            modelBuilder.Entity("MecuryProduct.Data.CustomerModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", "created_by")
                        .WithMany("customers")
                        .HasForeignKey("created_by_id");

                    b.Navigation("created_by");
                });

            modelBuilder.Entity("MecuryProduct.Data.NoteModel", b =>
                {
                    b.HasOne("MecuryProduct.Data.CustomerModel", null)
                        .WithMany("notes")
                        .HasForeignKey("CustomerModelId");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "corrected_by")
                        .WithMany()
                        .HasForeignKey("corrected_byId");

                    b.HasOne("MecuryProduct.Data.ApplicationUser", "created_by")
                        .WithMany("notes")
                        .HasForeignKey("created_by_id");

                    b.HasOne("MecuryProduct.Data.CarModel", "vehicle")
                        .WithMany("notes")
                        .HasForeignKey("veh_id");

                    b.Navigation("corrected_by");

                    b.Navigation("created_by");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MecuryProduct.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MecuryProduct.Data.ApplicationUser", b =>
                {
                    b.Navigation("cars");

                    b.Navigation("customers");

                    b.Navigation("driver_cars");

                    b.Navigation("notes");
                });

            modelBuilder.Entity("MecuryProduct.Data.CarModel", b =>
                {
                    b.Navigation("notes");
                });

            modelBuilder.Entity("MecuryProduct.Data.CustomerModel", b =>
                {
                    b.Navigation("cars");

                    b.Navigation("notes");
                });
#pragma warning restore 612, 618
        }
    }
}
